services:
  - type: web
    name: zeroroute
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: GROQ_API_KEY
        sync: false
      - key: SAMBANOVA_API_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: ROUTER_API_KEY
        sync: false
