name = "zeroroute-saas"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/assets"

[vars]
APP_URL = "https://zeroroute.mapki.in"
ADMIN_EMAIL = "admin@zeroroute.io"
DODO_ENVIRONMENT = "test_mode"
DODO_PRODUCT_ID = "pdt_0Nml3W2yZao32si4mSs6b"

[[d1_databases]]
binding = "DB"
database_name = "zeroroute-production"
database_id = "your-cloudflare-d1-database-id"
