export interface CatalogModel {
  id: string;
  name: string;
  brain: string;
  role: string;
  rpm: string;
  tpm?: string;
  rpd?: string;
  tpd?: string;
  latency: string;
  pool: string;
  highlight?: boolean;
  ctx: string;
  maxOut: string;
  kind?: string;
  isAudio?: boolean;
}

export interface CatalogCategory {
  name: string;
  description: string;
  models: CatalogModel[];
}

export interface ProviderCatalog {
  name: string;
  totalCapacity: string;
  poolType: "isolated" | "shared";
  poolBadge: string;
  poolSummary: string;
  categories: CatalogCategory[];
}

export const PROVIDER_PORTALS: Record<string, string> = {
  groq: "https://console.groq.com/keys",
  cerebras: "https://cloud.cerebras.ai/",
  sambanova: "https://cloud.sambanova.ai/",
  mistral: "https://console.mistral.ai/api-keys/",
  cloudflare: "https://dash.cloudflare.com/",
  gemini: "https://aistudio.google.com/app/apikey",
  openrouter: "https://openrouter.ai/keys",
  nvidia: "https://build.nvidia.com/",
  huggingface: "https://huggingface.co/settings/tokens",
  bazaarlink: "https://openrouter.ai/keys",
  cohere: "https://dashboard.cohere.com/api-keys",
};

export const PROVIDER_CATALOGS: Record<string, ProviderCatalog> = {
  mistral: {
    name: "Mistral AI",
    totalCapacity: "$10.00/mo Free Credit (~50M tokens) + Multi-Pool RPMs",
    poolType: "isolated",
    poolBadge: "🟢 Multi-Bucket Isolated RPMs",
    poolSummary:
      "Ministral 3B (750 RPM), Codestral (125 RPM), Pixtral (30 RPM), and Nemo (188 RPM) run in distinct speed buckets. $10 free credit resets every 30 days.",
    categories: [
      {
        name: "💬 Chat & General Instruct",
        description: "High quality multilingual European language models",
        models: [
          {
            id: "open-mistral-nemo",
            name: "Mistral NeMo 12B",
            brain: "12B Primary Workhorse",
            role: "Default chat model with rich reasoning and 128k context support",
            rpm: "188 RPM",
            tpm: "625k TPM",
            rpd: "$10 credit",
            latency: "~408ms",
            pool: "Nemo / 8B Shared Pool",
            highlight: true,
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
          {
            id: "ministral-3b-2512",
            name: "Ministral 3B",
            brain: "3B Ultra-High Throughput",
            role: "Massive 750 RPM rate limit bucket for high-frequency routing & agent loops",
            rpm: "750 RPM",
            tpm: "1.3M TPM",
            rpd: "$10 credit",
            latency: "~314ms",
            pool: "Isolated 3B Bucket",
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
          {
            id: "ministral-8b-2512",
            name: "Ministral 8B",
            brain: "8B Balanced Chat",
            role: "Balanced edge and server-side reasoning with low latency",
            rpm: "188 RPM",
            tpm: "625k TPM",
            rpd: "$10 credit",
            latency: "~449ms",
            pool: "Nemo / 8B Shared Pool",
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
          {
            id: "ministral-14b-2512",
            name: "Ministral 14B",
            brain: "14B High-Parameter Chat",
            role: "Dense reasoning and deep comprehension in an isolated 30 RPM pool",
            rpm: "30 RPM",
            tpm: "937.5k TPM",
            rpd: "$10 credit",
            latency: "~391ms",
            pool: "Isolated 14B Bucket",
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
          {
            id: "open-mistral-7b",
            name: "Mistral 7B Legacy",
            brain: "7B Open Model",
            role: "Classic 7B instruct model",
            rpm: "188 RPM",
            tpm: "625k TPM",
            rpd: "$10 credit",
            latency: "~445ms",
            pool: "Nemo / 8B Shared Pool",
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
        ],
      },
      {
        name: "💻 Code & Developer Specialists",
        description: "Dedicated code generation, SQL, JSON structure and FIM completion",
        models: [
          {
            id: "codestral-latest",
            name: "Codestral Latest 22B",
            brain: "22B Code Specialist",
            role: "Specialized 22B coding model with native Fill-in-the-Middle and 125 RPM pool",
            rpm: "125 RPM",
            tpm: "625k TPM",
            rpd: "$10 credit",
            latency: "~421ms",
            pool: "Isolated Codestral Bucket",
            ctx: "256k",
            maxOut: "8k",
            kind: "Code Specialist",
          },
          {
            id: "codestral-2508",
            name: "Codestral 2508",
            brain: "22B Code Specialist",
            role: "Stable pinned release of Codestral",
            rpm: "125 RPM",
            tpm: "625k TPM",
            rpd: "$10 credit",
            latency: "~407ms",
            pool: "Isolated Codestral Bucket",
            ctx: "256k",
            maxOut: "8k",
            kind: "Code Specialist",
          },
          {
            id: "mistral-code-latest",
            name: "Mistral Code Latest",
            brain: "22B Code API",
            role: "Latest automated coding endpoint",
            rpm: "125 RPM",
            tpm: "625k TPM",
            rpd: "$10 credit",
            latency: "~367ms",
            pool: "Isolated Codestral Bucket",
            ctx: "256k",
            maxOut: "8k",
            kind: "Code Specialist",
          },
        ],
      },
      {
        name: "👁️ Vision & Embeddings",
        description: "Multimodal image analysis, vector embeddings and moderation",
        models: [
          {
            id: "pixtral-12b-2409",
            name: "Pixtral 12B Vision",
            brain: "12B Multimodal Vision",
            role: "Native image understanding, chart reading & visual document extraction",
            rpm: "30 RPM",
            tpm: "937.5k TPM",
            rpd: "$10 credit",
            latency: "~367ms",
            pool: "Isolated Vision Bucket",
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
          {
            id: "mistral-embed",
            name: "Mistral Embed",
            brain: "1024-dim Semantic Vectors",
            role: "Dense text embeddings for search and retrieval augmented generation",
            rpm: "60 RPM",
            tpm: "—",
            rpd: "$10 credit",
            latency: "~743ms",
            pool: "Isolated Embedding Bucket",
            ctx: "8k",
            maxOut: "Embeddings",
            kind: "Vector Embedding",
          },
          {
            id: "codestral-embed",
            name: "Codestral Embed",
            brain: "Code & Dev Embeddings",
            role: "Specialized code embeddings for codebase search & semantic search",
            rpm: "60 RPM",
            tpm: "—",
            rpd: "$10 credit",
            latency: "~339ms",
            pool: "Isolated Embedding Bucket",
            ctx: "8k",
            maxOut: "Embeddings",
            kind: "Vector Embedding",
          },
          {
            id: "mistral-moderation-latest",
            name: "Mistral Moderation",
            brain: "Safety Classifier",
            role: "Content safety and toxicity classification across 9 hazard categories",
            rpm: "100 RPM",
            tpm: "—",
            rpd: "$10 credit",
            latency: "~283ms",
            pool: "Isolated Moderation Bucket",
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
        ],
      },
    ],
  },
  groq: {
    name: "Groq",
    totalCapacity: ">25,000 requests/day",
    poolType: "isolated",
    poolBadge: "🟢 100% Isolated Model Buckets",
    poolSummary:
      "Every Groq model runs in an independent rate-limit bucket. Consuming quota on one model (e.g. 120B) does NOT drain or affect other models.",
    categories: [
      {
        name: "💬 Chat & High-Intelligence",
        description: "High-parameter reasoning & ultra-low latency conversational models",
        models: [
          {
            id: "openai/gpt-oss-120b",
            name: "GPT-OSS 120B Flagship",
            brain: "120B MoE Flagship",
            role: "Primary flagship for deep reasoning, customer support bots & complex RAG",
            rpm: "30 RPM",
            tpm: "8k TPM",
            rpd: "1,000 RPD",
            tpd: "200k TPD",
            latency: "~540ms",
            pool: "Isolated Bucket",
            highlight: true,
            ctx: "128k",
            maxOut: "4k",
            kind: "High Intelligence",
          },
          {
            id: "qwen/qwen3.8-27b",
            name: "Qwen 3.8 27B",
            brain: "27B Ultra-Fast Chat",
            role: "Blazing sub-300ms speed with balanced 27B reasoning depth",
            rpm: "30 RPM",
            tpm: "8k TPM",
            rpd: "1,000 RPD",
            tpd: "200k TPD",
            latency: "~290ms",
            pool: "Isolated Bucket",
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
          {
            id: "openai/gpt-oss-20b",
            name: "GPT-OSS 20B",
            brain: "20B Fast Reasoning",
            role: "Lightweight 20B alternative for high volume traffic",
            rpm: "30 RPM",
            tpm: "8k TPM",
            rpd: "1,000 RPD",
            tpd: "200k TPD",
            latency: "~310ms",
            pool: "Isolated Bucket",
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
          {
            id: "qwen/qwen3.6-27b",
            name: "Qwen 3.6 27B (Reasoning)",
            brain: "27B CoT Deep Thinker",
            role: "Built-in <think> scratchpad reasoning for step-by-step logic & math",
            rpm: "30 RPM",
            tpm: "8k TPM",
            rpd: "1,000 RPD",
            tpd: "200k TPD",
            latency: "~400ms",
            pool: "Isolated Bucket",
            ctx: "128k",
            maxOut: "1k OTPM",
            kind: "Reasoning CoT",
          },
          {
            id: "allam-2-7b",
            name: "Allam 2 7B",
            brain: "7B High-Throughput",
            role: "Extreme 7,000 requests/day throughput, optimized for Arabic & English",
            rpm: "30 RPM",
            tpm: "6k TPM",
            rpd: "7,000 RPD",
            tpd: "500k TPD",
            latency: "~114ms",
            pool: "Isolated Bucket",
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
        ],
      },
      {
        name: "📚 Large-Context & Compound AI",
        description: "Massive 70,000 TPM limit + Unlimited Daily Tokens for large documents and RAG",
        models: [
          {
            id: "groq/compound-mini",
            name: "Groq Compound Mini",
            brain: "Compound AI (70k TPM)",
            role: "Massive 70k TPM + Unlimited Daily Tokens for large context injection & RAG",
            rpm: "30 RPM",
            tpm: "70k TPM",
            rpd: "250 RPD",
            tpd: "Unlimited",
            latency: "~570ms",
            pool: "Isolated Compound Pool",
            highlight: true,
            ctx: "128k",
            maxOut: "8k",
            kind: "Compound AI",
          },
          {
            id: "groq/compound",
            name: "Groq Compound",
            brain: "Compound AI Full",
            role: "Full Compound multi-agent reasoning pool with 70,000 TPM limit",
            rpm: "30 RPM",
            tpm: "70k TPM",
            rpd: "250 RPD",
            tpd: "Unlimited",
            latency: "~849ms",
            pool: "Isolated Compound Pool",
            ctx: "128k",
            maxOut: "8k",
            kind: "Compound AI",
          },
        ],
      },
      {
        name: "🛡️ Safety & Content Moderation",
        description: "Prompt injection, jailbreak detection, and safety classification",
        models: [
          {
            id: "meta-llama/llama-prompt-guard-2-86m",
            name: "Llama Prompt Guard 86M",
            brain: "86M Security Guard",
            role: "Deep prompt injection and jailbreak analysis (14,400 req/day)",
            rpm: "30 RPM",
            tpm: "15k TPM",
            rpd: "14,400 RPD",
            tpd: "500k TPD",
            latency: "~141ms",
            pool: "Isolated Guard Pool",
            ctx: "512",
            maxOut: "512",
            kind: "🛡️ Safety Guard",
          },
          {
            id: "meta-llama/llama-prompt-guard-2-22m",
            name: "Llama Prompt Guard 22M",
            brain: "22M Security Guard",
            role: "Ultra-fast lightweight prompt injection shield (14,400 req/day)",
            rpm: "30 RPM",
            tpm: "15k TPM",
            rpd: "14,400 RPD",
            tpd: "500k TPD",
            latency: "~152ms",
            pool: "Isolated Guard Pool",
            ctx: "512",
            maxOut: "512",
            kind: "🛡️ Safety Guard",
          },
          {
            id: "openai/gpt-oss-safeguard-20b",
            name: "GPT-OSS Safeguard 20B",
            brain: "20B Safety Classifier",
            role: "20B moderation and content safety filter",
            rpm: "30 RPM",
            tpm: "8k TPM",
            rpd: "1,000 RPD",
            tpd: "200k TPD",
            latency: "~132ms",
            pool: "Isolated Guard Pool",
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
        ],
      },
      {
        name: "🎙️ Speech-to-Text Audio",
        description: "8 Hours of free speech-to-text audio transcription every single day",
        models: [
          {
            id: "whisper-large-v3-turbo",
            name: "Whisper Large V3 Turbo",
            brain: "Fast Speech-to-Text",
            role: "Fast audio speech-to-text transcription (28,800 sec / 8 hours free daily)",
            rpm: "20 RPM",
            tpm: "—",
            rpd: "2,000 RPD",
            tpd: "28.8k sec/day",
            latency: "Fast STT",
            pool: "Isolated Audio Pool",
            isAudio: true,
            ctx: "25MB Audio",
            maxOut: "Audio STT",
            kind: "🎙️ Audio STT",
          },
          {
            id: "whisper-large-v3",
            name: "Whisper Large V3",
            brain: "Standard Speech-to-Text",
            role: "High-accuracy multilingual speech transcription (8 hours free daily)",
            rpm: "20 RPM",
            tpm: "—",
            rpd: "2,000 RPD",
            tpd: "28.8k sec/day",
            latency: "Standard STT",
            pool: "Isolated Audio Pool",
            isAudio: true,
            ctx: "25MB Audio",
            maxOut: "Audio STT",
            kind: "🎙️ Audio STT",
          },
        ],
      },
    ],
  },
  cloudflare: {
    name: "Cloudflare Workers AI",
    totalCapacity: "10,000 Neurons / day (~25k-100k req/day)",
    poolType: "shared",
    poolBadge: "🟡 Shared 10,000 Neuron Pool",
    poolSummary:
      "All Cloudflare Workers AI models share a single global account allowance of 10,000 Neurons/day. Lightweight models cost ~0.1-0.3 neurons/req, giving up to 100,000 free calls daily. Resets daily at 00:00 UTC.",
    categories: [
      {
        name: "💬 Chat & Instruction",
        description: "Ultra-fast global edge inference with sub-400ms latency",
        models: [
          {
            id: "@cf/meta/llama-3.1-8b-instruct",
            name: "Llama 3.1 8B Instruct",
            brain: "8B Ultra-Fast Chat",
            role: "Primary smart volume default (~0.35 neurons/req = ~28,500 req/day)",
            rpm: "300 RPM",
            tpm: "—",
            rpd: "~28,500/day",
            latency: "~390ms",
            pool: "Shared Neuron Pool",
            highlight: true,
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
          {
            id: "@cf/meta/llama-3.1-8b-instruct-fast",
            name: "Llama 3.1 8B Instruct Fast",
            brain: "8B Optimized Kernel",
            role: "Low latency kernel acceleration (~0.38 neurons = ~26,300 req/day)",
            rpm: "300 RPM",
            tpm: "—",
            rpd: "~26,300/day",
            latency: "~633ms",
            pool: "Shared Neuron Pool",
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
          {
            id: "@cf/meta/llama-3.1-70b-instruct",
            name: "Llama 3.1 70B Instruct",
            brain: "70B Dense Instruct",
            role: "70B heavyweight instruction (~1.48 neurons = ~6,750 req/day)",
            rpm: "300 RPM",
            tpm: "—",
            rpd: "~6,750/day",
            latency: "~668ms",
            pool: "Shared Neuron Pool",
            ctx: "128k",
            maxOut: "4k",
            kind: "High Intelligence",
          },
          {
            id: "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
            name: "Llama 3.3 70B FP8 Fast",
            brain: "70B Flagship Intelligence",
            role: "Heavyweight reasoning & complex instruction (~2.14 neurons/req)",
            rpm: "300 RPM",
            tpm: "—",
            rpd: "~4,600/day",
            latency: "~782ms",
            pool: "Shared Neuron Pool",
            ctx: "128k",
            maxOut: "4k",
            kind: "High Intelligence",
          },
          {
            id: "@cf/mistralai/mistral-small-3.1-24b-instruct",
            name: "Mistral Small 3.1 24B",
            brain: "24B Mistral Reasoning",
            role: "High quality European reasoning (~1.20 neurons/req = ~8,000 req/day)",
            rpm: "300 RPM",
            tpm: "—",
            rpd: "~8,000/day",
            latency: "~832ms",
            pool: "Shared Neuron Pool",
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
          {
            id: "@cf/meta/llama-4-scout-17b-16e-instruct",
            name: "Llama 4 Scout 17B",
            brain: "17B Next-Gen MoE",
            role: "Next-generation architecture preview (~0.80 neurons/req)",
            rpm: "300 RPM",
            tpm: "—",
            rpd: "~12,000/day",
            latency: "~561ms",
            pool: "Shared Neuron Pool",
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
          {
            id: "@cf/meta/llama-3.2-3b-instruct",
            name: "Llama 3.2 3B Instruct",
            brain: "3B Micro-Task Router",
            role: "High volume intent detection & routing (~0.31 neurons = ~32,000 req/day)",
            rpm: "300 RPM",
            tpm: "—",
            rpd: "~32,000/day",
            latency: "~360ms",
            pool: "Shared Neuron Pool",
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
          {
            id: "@cf/meta/llama-3.2-1b-instruct",
            name: "Llama 3.2 1B Instruct",
            brain: "1B Ultra-Lightweight",
            role: "Ultra high-volume classification (~0.10 neurons = ~100,000 req/day)",
            rpm: "300 RPM",
            tpm: "—",
            rpd: "~100,000/day",
            latency: "~510ms",
            pool: "Shared Neuron Pool",
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
        ],
      },
      {
        name: "💻 Code & Deep Reasoning",
        description: "Specialized programming assistants and chain-of-thought reasoners",
        models: [
          {
            id: "@cf/qwen/qwen2.5-coder-32b-instruct",
            name: "Qwen 2.5 Coder 32B",
            brain: "32B Code & SQL Specialist",
            role: "State-of-the-art coding, debugging & SQL generation (~1.50 neurons/req)",
            rpm: "300 RPM",
            tpm: "—",
            rpd: "~6,500/day",
            latency: "~912ms",
            pool: "Shared Neuron Pool",
            ctx: "256k",
            maxOut: "8k",
            kind: "Code Specialist",
          },
          {
            id: "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b",
            name: "DeepSeek R1 Distill 32B",
            brain: "32B Deep CoT Reasoning",
            role: "Step-by-step thinking scratchpad for logic and mathematics (~2.85 neurons)",
            rpm: "300 RPM",
            tpm: "—",
            rpd: "~3,500/day",
            latency: "~576ms",
            pool: "Shared Neuron Pool",
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
        ],
      },
      {
        name: "🌐 Vector Embeddings, Translation & Audio",
        description: "Semantic dense vectors, language translation and Whisper transcription",
        models: [
          {
            id: "@cf/baai/bge-large-en-v1.5",
            name: "BGE Large EN v1.5",
            brain: "1024-dim High-Accuracy RAG",
            role: "Dense semantic embeddings (~0.06 neurons/req = ~160,000 vectors/day)",
            rpm: "300 RPM",
            tpm: "—",
            rpd: "~160,000/day",
            latency: "~212ms",
            pool: "Shared Neuron Pool",
            ctx: "512",
            maxOut: "Embeddings",
            kind: "Vector Embedding",
          },
          {
            id: "@cf/baai/bge-base-en-v1.5",
            name: "BGE Base EN v1.5",
            brain: "768-dim Balanced",
            role: "Balanced speed/accuracy vector search (~0.04 neurons = ~250,000 vectors/day)",
            rpm: "300 RPM",
            tpm: "—",
            rpd: "~250,000/day",
            latency: "~140ms",
            pool: "Shared Neuron Pool",
            ctx: "512",
            maxOut: "Embeddings",
            kind: "Vector Embedding",
          },
          {
            id: "@cf/meta/m2m100-1.2b",
            name: "M2M100 1.2B Translation",
            brain: "Direct Multi-Language",
            role: "Direct translation between 100 language pairs without English pivot",
            rpm: "300 RPM",
            tpm: "—",
            rpd: "~45,000/day",
            latency: "~740ms",
            pool: "Shared Neuron Pool",
            ctx: "1k",
            maxOut: "Translation",
            kind: "🌐 Translation",
          },
          {
            id: "@cf/openai/whisper",
            name: "OpenAI Whisper CF",
            brain: "Speech-to-Text Edge",
            role: "Audio speech transcription at the edge",
            rpm: "300 RPM",
            tpm: "—",
            rpd: "Shared 10k",
            latency: "~850ms",
            pool: "Shared Neuron Pool",
            isAudio: true,
            ctx: "25MB Audio",
            maxOut: "Audio STT",
            kind: "🎙️ Audio STT",
          },
        ],
      },
    ],
  },
  cohere: {
    name: "Cohere",
    totalCapacity: "1,000 Calls / month (40 RPM Throttle)",
    poolType: "shared",
    poolBadge: "🟡 Shared 1,000 Calls/Month Pool",
    poolSummary:
      "All Cohere trial endpoints share a unified monthly allowance of 1,000 API calls and a 40 RPM speed throttle across chat, embed, vision, and rerank.",
    categories: [
      {
        name: "💬 Chat & Large-Context Foundation",
        description: "Enterprise grade instruction and massive context document reasoning",
        models: [
          {
            id: "command-r-plus-08-2024",
            name: "Command R+ 08-2024",
            brain: "Enterprise Production RAG",
            role: "Default enterprise chat and RAG with 128k context and citation generation",
            rpm: "40 RPM",
            tpm: "—",
            rpd: "1,000/mo",
            latency: "~470ms",
            pool: "Shared Trial Pool",
            highlight: true,
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
          {
            id: "command-a-03-2025",
            name: "Command A 03-2025",
            brain: "Fast Large-Context Reasoning",
            role: "Fast large-context instruction following with 288,000 token context",
            rpm: "40 RPM",
            tpm: "—",
            rpd: "1,000/mo",
            latency: "~380ms",
            pool: "Shared Trial Pool",
            highlight: true,
            ctx: "288k",
            maxOut: "4k",
            kind: "Chat",
          },
          {
            id: "command-a-plus-05-2026",
            name: "Command A+ 05-2026",
            brain: "436k Massive Context",
            role: "Massive 436,000 token context window for large books and document analysis",
            rpm: "40 RPM",
            tpm: "—",
            rpd: "1,000/mo",
            latency: "~530ms",
            pool: "Shared Trial Pool",
            ctx: "436k",
            maxOut: "4k",
            kind: "Chat",
          },
          {
            id: "command-a-reasoning-08-2025",
            name: "Command A Reasoning",
            brain: "Step-by-Step Deep CoT",
            role: "Deep chain-of-thought step-by-step logic with 288k context",
            rpm: "40 RPM",
            tpm: "—",
            rpd: "1,000/mo",
            latency: "~1,240ms",
            pool: "Shared Trial Pool",
            ctx: "288k",
            maxOut: "4k",
            kind: "Reasoning CoT",
          },
          {
            id: "command-r-08-2024",
            name: "Command R 08-2024",
            brain: "Enterprise Instruct",
            role: "Standard enterprise instruct model with 128k context",
            rpm: "40 RPM",
            tpm: "—",
            rpd: "1,000/mo",
            latency: "~710ms",
            pool: "Shared Trial Pool",
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
          {
            id: "command-r7b-12-2024",
            name: "Command R 7B",
            brain: "7B Lightweight Chat",
            role: "High-speed lightweight enterprise chat with 132k context",
            rpm: "40 RPM",
            tpm: "—",
            rpd: "1,000/mo",
            latency: "~415ms",
            pool: "Shared Trial Pool",
            ctx: "132k",
            maxOut: "4k",
            kind: "Chat",
          },
          {
            id: "command-r7b-arabic-02-2025",
            name: "Command R 7B Arabic",
            brain: "7B Arabic NLP Specialist",
            role: "Specialized Arabic language processing and conversation with 128k context",
            rpm: "40 RPM",
            tpm: "—",
            rpd: "1,000/mo",
            latency: "~440ms",
            pool: "Shared Trial Pool",
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
        ],
      },
      {
        name: "🧠 Multimodal, Code & Specialized Reasoning",
        description: "Vision understanding, code generation and translation engines",
        models: [
          {
            id: "command-a-vision-07-2025",
            name: "Command A Vision",
            brain: "Multimodal Vision Analysis",
            role: "High-resolution multimodal vision analysis and document OCR",
            rpm: "40 RPM",
            tpm: "—",
            rpd: "1,000/mo",
            latency: "~365ms",
            pool: "Shared Trial Pool",
            ctx: "128k",
            maxOut: "4k",
            kind: "Multimodal",
          },
          {
            id: "c4ai-aya-vision-32b",
            name: "Aya Vision 32B",
            brain: "32B Multilingual Vision",
            role: "Multilingual vision understanding and image interpretation",
            rpm: "40 RPM",
            tpm: "—",
            rpd: "1,000/mo",
            latency: "~420ms",
            pool: "Shared Trial Pool",
            ctx: "16k",
            maxOut: "4k",
            kind: "Multimodal",
          },
          {
            id: "north-mini-code-1-0",
            name: "North Mini Code 1.0",
            brain: "Code Specialist",
            role: "Lightweight high-speed coding assistant and syntax completion",
            rpm: "40 RPM",
            tpm: "—",
            rpd: "1,000/mo",
            latency: "~410ms",
            pool: "Shared Trial Pool",
            ctx: "32k",
            maxOut: "4k",
            kind: "Code Specialist",
          },
          {
            id: "command-a-translate-08-2025",
            name: "Command A Translate",
            brain: "Translation Engine",
            role: "Fast low-latency cross-lingual translation engine",
            rpm: "40 RPM",
            tpm: "—",
            rpd: "1,000/mo",
            latency: "~375ms",
            pool: "Shared Trial Pool",
            ctx: "8k",
            maxOut: "4k",
            kind: "Chat",
          },
        ],
      },
      {
        name: "🌐 Global Multilingual (Aya Series)",
        description: "Flagship cross-lingual reasoning across 50+ world languages",
        models: [
          {
            id: "c4ai-aya-expanse-32b",
            name: "Aya Expanse 32B",
            brain: "32B Flagship Multilingual",
            role: "State-of-the-art multilingual reasoning across 50+ languages with 128k context",
            rpm: "40 RPM",
            tpm: "—",
            rpd: "1,000/mo",
            latency: "~430ms",
            pool: "Shared Trial Pool",
            highlight: true,
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
          {
            id: "tiny-aya-global",
            name: "Tiny Aya Global",
            brain: "Edge Multilingual",
            role: "Compact edge multilingual model for lightweight deployments",
            rpm: "40 RPM",
            tpm: "—",
            rpd: "1,000/mo",
            latency: "~390ms",
            pool: "Shared Trial Pool",
            ctx: "8k",
            maxOut: "4k",
            kind: "Chat",
          },
        ],
      },
      {
        name: "🔍 Vector Embeddings",
        description: "Dense semantic text embeddings for enterprise search and RAG",
        models: [
          {
            id: "embed-english-v3.0",
            name: "Embed English v3.0",
            brain: "1024-dim Dense English",
            role: "Enterprise English dense vector search",
            rpm: "40 RPM",
            tpm: "—",
            rpd: "1,000/mo",
            latency: "~344ms",
            pool: "Shared Trial Pool",
            ctx: "8k",
            maxOut: "Embeddings",
            kind: "Vector Embedding",
          },
          {
            id: "embed-multilingual-v3.0",
            name: "Embed Multilingual v3.0",
            brain: "1024-dim Multilingual",
            role: "Enterprise multilingual retrieval for 100+ languages",
            rpm: "40 RPM",
            tpm: "—",
            rpd: "1,000/mo",
            latency: "~338ms",
            pool: "Shared Trial Pool",
            ctx: "8k",
            maxOut: "Embeddings",
            kind: "Vector Embedding",
          },
          {
            id: "embed-english-light-v3.0",
            name: "Embed English Light v3.0",
            brain: "384-dim English Light",
            role: "High-speed lightweight English vector search",
            rpm: "40 RPM",
            tpm: "—",
            rpd: "1,000/mo",
            latency: "~345ms",
            pool: "Shared Trial Pool",
            ctx: "8k",
            maxOut: "Embeddings",
            kind: "Vector Embedding",
          },
          {
            id: "embed-multilingual-light-v3.0",
            name: "Embed Multilingual Light v3.0",
            brain: "384-dim Multilingual Light",
            role: "Lightweight multilingual vector indexing for 100+ languages",
            rpm: "40 RPM",
            tpm: "—",
            rpd: "1,000/mo",
            latency: "~336ms",
            pool: "Shared Trial Pool",
            ctx: "8k",
            maxOut: "Embeddings",
            kind: "Vector Embedding",
          },
        ],
      },
    ],
  },
  sambanova: {
    name: "SambaNova Cloud",
    totalCapacity: "Hardware RDU Dedicated Tier-1 Free Allocation",
    poolType: "isolated",
    poolBadge: "🟢 Dedicated RDU Queue (MiniMax)",
    poolSummary:
      "MiniMax-M2.7 runs on dedicated hardware RDU compute with 100% pass rates (~500ms). High-demand models (70B, 120B, DeepSeek) share an open queue that can throttle during peak hours.",
    categories: [
      {
        name: "🟢 Tier-1 Production Ready (Dedicated Queues)",
        description: "High reliability dedicated hardware queues with ultra-low latency",
        models: [
          {
            id: "MiniMax-M2.7",
            name: "MiniMax M2.7 Flagship",
            brain: "Dedicated Hardware RDU",
            role: "Primary ultra-fast default with 100% pass rate and 32k context",
            rpm: "100 RPM",
            tpm: "Dedicated",
            rpd: "Unlimited",
            latency: "~500ms",
            pool: "Dedicated RDU Queue",
            highlight: true,
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
          {
            id: "gemma-4-31B-it",
            name: "Gemma 4 31B Instruct",
            brain: "31B High-Reasoning",
            role: "High-parameter open weights reasoning model on dedicated queue",
            rpm: "60 RPM",
            tpm: "Dedicated",
            rpd: "Unlimited",
            latency: "~990ms",
            pool: "Dedicated Gemma Queue",
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
        ],
      },
      {
        name: "⚡ High-Demand Open Weights (Shared Queue)",
        description: "Flagship open models on shared compute queues (auto-fallbacks to MiniMax on 429)",
        models: [
          {
            id: "Meta-Llama-3.3-70B-Instruct",
            name: "Llama 3.3 70B Instruct",
            brain: "70B Dense Heavyweight",
            role: "Heavyweight 70B instruction following",
            rpm: "30 RPM",
            tpm: "Shared",
            rpd: "Demand-based",
            latency: "~550ms",
            pool: "Shared RDU Queue",
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
          {
            id: "gpt-oss-120b",
            name: "GPT-OSS 120B",
            brain: "120B Flagship Intelligence",
            role: "120B high intelligence reasoning",
            rpm: "30 RPM",
            tpm: "Shared",
            rpd: "Demand-based",
            latency: "~510ms",
            pool: "Shared RDU Queue",
            ctx: "128k",
            maxOut: "4k",
            kind: "High Intelligence",
          },
          {
            id: "DeepSeek-V3.1",
            name: "DeepSeek V3.1 General",
            brain: "DeepSeek V3.1 General",
            role: "DeepSeek general foundation model",
            rpm: "30 RPM",
            tpm: "Shared",
            rpd: "Demand-based",
            latency: "~515ms",
            pool: "Shared RDU Queue",
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
          {
            id: "DeepSeek-V3.2",
            name: "DeepSeek V3.2 Reasoning",
            brain: "DeepSeek V3.2 Reasoning",
            role: "DeepSeek V3.2 advanced CoT reasoning model",
            rpm: "30 RPM",
            tpm: "Shared",
            rpd: "Demand-based",
            latency: "~519ms",
            pool: "Shared RDU Queue",
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
          {
            id: "MiniMax-M3",
            name: "MiniMax M3 Next-Gen",
            brain: "MiniMax M3 Flagship",
            role: "Next-generation MiniMax foundation model with 32k context",
            rpm: "30 RPM",
            tpm: "Shared",
            rpd: "Demand-based",
            latency: "~747ms",
            pool: "Shared RDU Queue",
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
        ],
      },
    ],
  },
  gemini: {
    name: "Google Gemini",
    totalCapacity: ">30,000 requests/day (Aggregate Across Model Pools)",
    poolType: "isolated",
    poolBadge: "🟢 100% Isolated Model Buckets",
    poolSummary:
      "Every Gemini model runs in a separate, dedicated rate-limit bucket. Flash-Lite (500 RPD), Gemma (14,400 RPD), and Frontier Flash (20 RPD) are 100% isolated and never cross-deplete.",
    categories: [
      {
        name: "⚡ Flash-Lite & High-Throughput Workhorses",
        description: "Ultra-low latency default chat, structured extraction & 1M context analysis",
        models: [
          {
            id: "gemini-3.5-flash-lite",
            name: "Gemini 3.5 Flash Lite",
            brain: "High-Throughput Edge Inference",
            role: "Primary default chat model with sub-second response times and 1M context",
            rpm: "15 RPM",
            tpm: "250k TPM",
            rpd: "500 RPD",
            latency: "~310ms",
            pool: "Isolated Flash-Lite Bucket",
            highlight: true,
            ctx: "1M",
            maxOut: "8k",
            kind: "Multimodal",
          },
          {
            id: "gemini-flash-lite-latest",
            name: "Gemini Flash Lite Latest",
            brain: "Latest Stable Flash-Lite Alias",
            role: "Auto-updating alias tracking latest Google Flash Lite model",
            rpm: "15 RPM",
            tpm: "250k TPM",
            rpd: "500 RPD",
            latency: "~320ms",
            pool: "Isolated Flash-Lite Bucket",
            ctx: "1M",
            maxOut: "8k",
            kind: "Multimodal",
          },
          {
            id: "gemini-3.1-flash-lite",
            name: "Gemini 3.1 Flash Lite",
            brain: "3.1 Flash-Lite Secondary",
            role: "High-quota secondary Flash-Lite fallback with 1M context",
            rpm: "15 RPM",
            tpm: "250k TPM",
            rpd: "500 RPD",
            latency: "~450ms",
            pool: "Isolated Flash-Lite Bucket",
            ctx: "1M",
            maxOut: "8k",
            kind: "Multimodal",
          },
        ],
      },
      {
        name: "🔥 Gemma High-Quota Open-Weights (14,400 RPD)",
        description: "Massive 14,400 requests/day dedicated quota open-weights workhorses",
        models: [
          {
            id: "gemma-4-31b-it",
            name: "Gemma 4 31B Instruct",
            brain: "31B Open-Weights Flagship",
            role: "Massive 14,400 requests/day quota workhorse for extreme traffic absorption",
            rpm: "30 RPM",
            tpm: "16k TPM",
            rpd: "14,400 RPD",
            latency: "~620ms",
            pool: "Isolated Gemma Bucket",
            highlight: true,
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
          {
            id: "gemma-4-26b-a4b-it",
            name: "Gemma 4 26B Instruct",
            brain: "26B High-Throughput",
            role: "Secondary 14,400 requests/day open weights model",
            rpm: "30 RPM",
            tpm: "16k TPM",
            rpd: "14,400 RPD",
            latency: "~550ms",
            pool: "Isolated Gemma Bucket",
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
        ],
      },
      {
        name: "🧠 Frontier & Reasoning Flash",
        description: "Frontier multimodal intelligence, deep comprehension and agentic reasoning",
        models: [
          {
            id: "gemini-3.7-flash",
            name: "Gemini 3.7 Flash",
            brain: "Frontier Hybrid Reasoning",
            role: "Flagship frontier reasoning, complex logic, and agentic workflows",
            rpm: "5 RPM",
            tpm: "250k TPM",
            rpd: "20 RPD",
            latency: "~846ms",
            pool: "Isolated 3.7-Flash Bucket",
            ctx: "1M",
            maxOut: "8k",
            kind: "Multimodal",
          },
          {
            id: "gemini-3.8-flash",
            name: "Gemini 3.8 Flash",
            brain: "Frontier Flash Preview",
            role: "Advanced frontier generation with 1M context",
            rpm: "5 RPM",
            tpm: "250k TPM",
            rpd: "20 RPD",
            latency: "~890ms",
            pool: "Isolated 3.8-Flash Bucket",
            ctx: "1M",
            maxOut: "8k",
            kind: "Multimodal",
          },
          {
            id: "gemini-3.6-flash",
            name: "Gemini 3.6 Flash",
            brain: "Next-Gen Frontier Flash",
            role: "Hybrid reasoning and instant response speed with multimodal capabilities",
            rpm: "5 RPM",
            tpm: "250k TPM",
            rpd: "20 RPD",
            latency: "~560ms",
            pool: "Isolated 3.6-Flash Bucket",
            ctx: "1M",
            maxOut: "8k",
            kind: "Multimodal",
          },
          {
            id: "gemini-3.5-flash",
            name: "Gemini 3.5 Flash",
            brain: "1M Context Flash",
            role: "Standard Flash baseline with rich reasoning and 1M tokens context",
            rpm: "5 RPM",
            tpm: "250k TPM",
            rpd: "20 RPD",
            latency: "~420ms",
            pool: "Isolated Flash Bucket",
            ctx: "1M",
            maxOut: "8k",
            kind: "Multimodal",
          },
          {
            id: "gemini-3-flash-preview",
            name: "Gemini 3 Flash Preview",
            brain: "Experimental Flash",
            role: "Experimental Flash architecture preview",
            rpm: "5 RPM",
            tpm: "250k TPM",
            rpd: "20 RPD",
            latency: "~829ms",
            pool: "Isolated Preview Bucket",
            ctx: "1M",
            maxOut: "8k",
            kind: "Multimodal",
          },
          {
            id: "gemini-flash-latest",
            name: "Gemini Flash Latest",
            brain: "Stable Flash Alias",
            role: "Stable Flash pointer to active release",
            rpm: "5 RPM",
            tpm: "250k TPM",
            rpd: "20 RPD",
            latency: "~650ms",
            pool: "Isolated Flash Bucket",
            ctx: "1M",
            maxOut: "8k",
            kind: "Multimodal",
          },
          {
            id: "gemini-robotics-er-2-preview",
            name: "Gemini Robotics ER 2",
            brain: "Embodied Reasoning",
            role: "Embodied reasoning and visual physical understanding",
            rpm: "5 RPM",
            tpm: "250k TPM",
            rpd: "20 RPD",
            latency: "~1,117ms",
            pool: "Isolated Robotics Bucket",
            ctx: "1M",
            maxOut: "8k",
            kind: "Multimodal",
          },
        ],
      },
      {
        name: "🔍 Vector Embeddings & Audio",
        description: "Dense 3,072-dim vector embeddings and audio speech processing",
        models: [
          {
            id: "gemini-embedding-001",
            name: "Gemini Embedding 001",
            brain: "3,072-dim Dense Vectors",
            role: "Enterprise dense text embeddings for search and knowledge base retrieval",
            rpm: "100 RPM",
            tpm: "—",
            rpd: "1,000 RPD",
            latency: "~454ms",
            pool: "Isolated Embedding Bucket",
            ctx: "8k",
            maxOut: "Embeddings",
            kind: "Vector Embedding",
          },
          {
            id: "gemini-embedding-2",
            name: "Gemini Embedding 2",
            brain: "Next-Gen Dense Vectors",
            role: "High-precision vector retrieval and semantic similarity",
            rpm: "100 RPM",
            tpm: "—",
            rpd: "1,000 RPD",
            latency: "~563ms",
            pool: "Isolated Embedding Bucket",
            ctx: "8k",
            maxOut: "Embeddings",
            kind: "Vector Embedding",
          },
          {
            id: "text-embedding-004",
            name: "Text Embedding 004",
            brain: "Semantic Embeddings",
            role: "Vector search, document retrieval & clustering (768 dims)",
            rpm: "60 RPM",
            tpm: "100k TPM",
            rpd: "1,000 RPD",
            latency: "~220ms",
            pool: "Isolated Embedding Bucket",
            ctx: "8k",
            maxOut: "Embeddings",
            kind: "Vector Embedding",
          },
          {
            id: "gemini-3.5-transcribe",
            name: "Gemini 3.5 Transcribe",
            brain: "Audio Engine",
            role: "Direct speech and audio processing",
            rpm: "3 RPM",
            tpm: "10k TPM",
            rpd: "25 RPD",
            latency: "~483ms",
            pool: "Isolated Audio Bucket",
            isAudio: true,
            ctx: "20MB Audio",
            maxOut: "Audio STT",
            kind: "🎙️ Audio STT",
          },
        ],
      },
    ],
  },
  openrouter: {
    name: "OpenRouter",
    totalCapacity: "200 Requests / day (20 RPM Global Free Throttle)",
    poolType: "shared",
    poolBadge: "🟡 Shared 200 RPD / 20 RPM Pool",
    poolSummary:
      "All OpenRouter :free models share an account-wide allowance of 200 requests/day and 20 RPM speed throttle. Native 3-model fallback arrays supported.",
    categories: [
      {
        name: "💬 Chat, Reasoning & Code",
        description: "Massive variety of free open-weights foundation models",
        models: [
          {
            id: "nvidia/nemotron-3-super-120b-a12b:free",
            name: "NVIDIA Nemotron 3 Super 120B",
            brain: "120B MoE Ultra-Fast Workhorse",
            role: "Primary flagship 120B MoE with ultra-low ~142ms latency and 262k context",
            rpm: "20 RPM",
            tpm: "—",
            rpd: "200 RPD",
            latency: "~142ms",
            pool: "Shared Account Pool",
            highlight: true,
            ctx: "262k",
            maxOut: "4k",
            kind: "High Intelligence",
          },
          {
            id: "nvidia/nemotron-3.5-lightning:free",
            name: "Nemotron 3.5 Lightning",
            brain: "1M Context Deep Reasoning",
            role: "Massive 1,000,000 context window with step-by-step reasoning",
            rpm: "20 RPM",
            tpm: "—",
            rpd: "200 RPD",
            latency: "~276ms",
            pool: "Shared Account Pool",
            highlight: true,
            ctx: "1M",
            maxOut: "4k",
            kind: "Chat",
          },
          {
            id: "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free",
            name: "Nemotron 3 Nano Omni 30B",
            brain: "30B Fast Reasoning",
            role: "Ultra-fast compact 30B reasoning model with 256k context",
            rpm: "20 RPM",
            tpm: "—",
            rpd: "200 RPD",
            latency: "~223ms",
            pool: "Shared Account Pool",
            ctx: "256k",
            maxOut: "4k",
            kind: "Reasoning CoT",
          },
          {
            id: "openrouter/free",
            name: "OpenRouter Free Auto-Router",
            brain: "Multi-Cloud Free Router",
            role: "Intelligent auto-cascading router choosing fastest available free model",
            rpm: "20 RPM",
            tpm: "—",
            rpd: "200 RPD",
            latency: "~380ms",
            pool: "Shared Account Pool",
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
          {
            id: "cohere/north-mini-code:free",
            name: "Cohere North Mini Code Free",
            brain: "Cohere Code Reasoning",
            role: "Lightweight code assistance and reasoning on free tier",
            rpm: "20 RPM",
            tpm: "—",
            rpd: "200 RPD",
            latency: "~341ms",
            pool: "Shared Account Pool",
            ctx: "256k",
            maxOut: "4k",
            kind: "Code Specialist",
          },
          {
            id: "poolside/laguna-xs-2.1:free",
            name: "Poolside Laguna XS 2.1",
            brain: "Fast General Instruction",
            role: "Ultra-fast lightweight general instruction following model",
            rpm: "20 RPM",
            tpm: "—",
            rpd: "200 RPD",
            latency: "~421ms",
            pool: "Shared Account Pool",
            ctx: "262k",
            maxOut: "4k",
            kind: "Chat",
          },
          {
            id: "inclusionai/ling-3.0-flash-fin:free",
            name: "Ling 3.0 Flash Fin",
            brain: "Financial Specialist",
            role: "Specialized financial data, accounting & quantitative analysis",
            rpm: "20 RPM",
            tpm: "—",
            rpd: "200 RPD",
            latency: "~645ms",
            pool: "Shared Account Pool",
            ctx: "262k",
            maxOut: "4k",
            kind: "Chat",
          },
          {
            id: "inclusionai/ling-3.0-flash-sante:free",
            name: "Ling 3.0 Flash Santé",
            brain: "Medical Specialist",
            role: "Specialized healthcare and biomedical knowledge reasoning",
            rpm: "20 RPM",
            tpm: "—",
            rpd: "200 RPD",
            latency: "~779ms",
            pool: "Shared Account Pool",
            ctx: "262k",
            maxOut: "4k",
            kind: "Chat",
          },
          {
            id: "dots-studio/dots-3-note-preview:free",
            name: "Dots-3 Note Preview",
            brain: "512k Long Document Note",
            role: "Large 512,000 token context window for document summarization",
            rpm: "20 RPM",
            tpm: "—",
            rpd: "200 RPD",
            latency: "~786ms",
            pool: "Shared Account Pool",
            ctx: "512k",
            maxOut: "4k",
            kind: "Chat",
          },
          {
            id: "liquid/lfm-2.5-2.6b:free",
            name: "Liquid LFM 2.5 2.6B Free",
            brain: "2.6B Ultra-Fast Liquid Model",
            role: "High-speed liquid neural network for chat and instruction",
            rpm: "20 RPM",
            tpm: "—",
            rpd: "200 RPD",
            latency: "~410ms",
            pool: "Shared Account Pool",
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
          {
            id: "minimax/minimax-m2.7:free",
            name: "MiniMax M2.7 Free",
            brain: "MiniMax Conversational",
            role: "Conversational chat fallback on OpenRouter free tier",
            rpm: "20 RPM",
            tpm: "—",
            rpd: "200 RPD",
            latency: "~1,200ms",
            pool: "Shared Account Pool",
            ctx: "196k",
            maxOut: "4k",
            kind: "Chat",
          },
          {
            id: "google/gemma-4-31b-it:free",
            name: "Gemma 4 31B Free",
            brain: "31B Open Weights",
            role: "Google open-weights reasoning model hosted on OpenRouter",
            rpm: "20 RPM",
            tpm: "—",
            rpd: "200 RPD",
            latency: "~1,304ms",
            pool: "Shared Account Pool",
            ctx: "262k",
            maxOut: "4k",
            kind: "Chat",
          },
        ],
      },
      {
        name: "🛡️ Safety, Embeddings & Audio",
        description: "Input/output guardrails, dense semantic embeddings and text-to-speech",
        models: [
          {
            id: "nvidia/nemotron-3.5-content-safety:free",
            name: "Nemotron 3.5 Content Safety",
            brain: "Input/Output Guardrail",
            role: "Real-time prompt injection and toxicity guardrail",
            rpm: "20 RPM",
            tpm: "—",
            rpd: "200 RPD",
            latency: "~200ms",
            pool: "Shared Account Pool",
            ctx: "128k",
            maxOut: "4k",
            kind: "🛡️ Safety Guard",
          },
          {
            id: "nvidia/llama-nemotron-embed-vl-1b-v2:free",
            name: "Nemotron Embed VL 1B",
            brain: "2048-dim Dense Vectors",
            role: "Dense semantic text embeddings for search and RAG",
            rpm: "20 RPM",
            tpm: "—",
            rpd: "200 RPD",
            latency: "~491ms",
            pool: "Shared Account Pool",
            ctx: "32k",
            maxOut: "Embeddings",
            kind: "Vector Embedding",
          },
          {
            id: "fish-audio/s2.1-pro:free",
            name: "Fish Audio S2.1 Pro",
            brain: "Speech Synthesis",
            role: "Text-to-speech audio voice generation",
            rpm: "20 RPM",
            tpm: "—",
            rpd: "200 RPD",
            latency: "TTS",
            pool: "Shared Account Pool",
            isAudio: true,
            ctx: "TTS",
            maxOut: "Audio",
            kind: "🎙️ Audio STT",
          },
        ],
      },
    ],
  },
  nvidia: {
    name: "NVIDIA NIM",
    totalCapacity: "1,000 Free Credits on Signup",
    poolType: "shared",
    poolBadge: "🟢 NVIDIA DGX Cloud Accelerators",
    poolSummary:
      "Enterprise containerized microservices running on NVIDIA DGX H100/H200 Tensor Core GPUs. 1,000 trial credits shared across all models.",
    categories: [
      {
        name: "🚀 Accelerated Foundation Models",
        description: "Optimized TensorRT-LLM engines on DGX Cloud infrastructure",
        models: [
          {
            id: "nvidia/nemotron-3.5-lightning-30b-a3b",
            name: "Nemotron 3.5 Lightning 30B",
            brain: "30B MoE Fast Reasoning",
            role: "Primary 30B step-by-step reasoning on NVIDIA NIM",
            rpm: "60 RPM",
            tpm: "—",
            rpd: "Free Credits",
            latency: "~210ms",
            pool: "NIM Free Credits",
            highlight: true,
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
          {
            id: "nvidia/nemotron-3-super-120b-a12b",
            name: "Nemotron 3 Super 120B",
            brain: "120B Sparse MoE Flagship",
            role: "120B high intelligence reasoning model",
            rpm: "60 RPM",
            tpm: "—",
            rpd: "Free Credits",
            latency: "~320ms",
            pool: "NIM Free Credits",
            highlight: true,
            ctx: "128k",
            maxOut: "4k",
            kind: "High Intelligence",
          },
          {
            id: "deepseek-ai/deepseek-r1",
            name: "DeepSeek R1 Flagship",
            brain: "Full 671B Deep Reasoning",
            role: "Full scale 671B deep reasoning on GPU cluster",
            rpm: "60 RPM",
            tpm: "—",
            rpd: "Free Credits",
            latency: "~950ms",
            pool: "NIM Free Credits",
            ctx: "128k",
            maxOut: "4k",
            kind: "Reasoning CoT",
          },
          {
            id: "deepseek-ai/deepseek-v3",
            name: "DeepSeek V3 671B",
            brain: "671B MoE Foundation",
            role: "Full scale 671B general foundation model",
            rpm: "60 RPM",
            tpm: "—",
            rpd: "Free Credits",
            latency: "~890ms",
            pool: "NIM Free Credits",
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
          {
            id: "meta/llama-3.2-11b-vision-instruct",
            name: "Llama 3.2 11B Vision",
            brain: "11B Multimodal Vision",
            role: "Multimodal image and visual document reasoning",
            rpm: "60 RPM",
            tpm: "—",
            rpd: "Free Credits",
            latency: "~410ms",
            pool: "NIM Free Credits",
            ctx: "128k",
            maxOut: "4k",
            kind: "Multimodal",
          },
          {
            id: "mistralai/mistral-large-2-instruct",
            name: "Mistral Large 2",
            brain: "123B Flagship Mistral",
            role: "High-parameter multilingual reasoning model",
            rpm: "60 RPM",
            tpm: "—",
            rpd: "Free Credits",
            latency: "~720ms",
            pool: "NIM Free Credits",
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
          {
            id: "google/gemma-4-31b-it",
            name: "Gemma 4 31B NIM",
            brain: "31B Google Open Weights",
            role: "31B open weights instruct model on DGX Cloud",
            rpm: "60 RPM",
            tpm: "—",
            rpd: "Free Credits",
            latency: "~650ms",
            pool: "NIM Free Credits",
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
        ],
      },
      {
        name: "🔍 Embeddings & Retrieval",
        description: "Dense vector retrieval models on TensorRT infrastructure",
        models: [
          {
            id: "nvidia/embed-qa-4",
            name: "NVIDIA Embed QA 4",
            brain: "QA Retrieval Vectors",
            role: "Dense semantic question-answering retrieval",
            rpm: "60 RPM",
            tpm: "—",
            rpd: "Free Credits",
            latency: "~310ms",
            pool: "NIM Free Credits",
            ctx: "8k",
            maxOut: "Embeddings",
            kind: "Vector Embedding",
          },
          {
            id: "nvidia/llama-3.2-nv-embedqa-1b-v1",
            name: "NV EmbedQA 1B",
            brain: "Multimodal Retrieval",
            role: "Lightweight 1B question answering embeddings",
            rpm: "60 RPM",
            tpm: "—",
            rpd: "Free Credits",
            latency: "~240ms",
            pool: "NIM Free Credits",
            ctx: "8k",
            maxOut: "Embeddings",
            kind: "Vector Embedding",
          },
          {
            id: "snowflake/arctic-embed-l",
            name: "Snowflake Arctic Embed L",
            brain: "Arctic Dense Vectors",
            role: "Enterprise dense text embedding",
            rpm: "60 RPM",
            tpm: "—",
            rpd: "Free Credits",
            latency: "~290ms",
            pool: "NIM Free Credits",
            ctx: "8k",
            maxOut: "Embeddings",
            kind: "Vector Embedding",
          },
        ],
      },
    ],
  },
  huggingface: {
    name: "Hugging Face Inference",
    totalCapacity: "1,000 req / 5 min (200 RPM, ~288k req/day)",
    poolType: "shared",
    poolBadge: "🟡 Shared 200 RPM Hub Pool",
    poolSummary:
      "Native serverless inference models share a rolling 200 RPM / 1,000 req per 5 min Hub limit. Extreme throughput for embeddings and classifiers.",
    categories: [
      {
        name: "💬 Serverless Chat & Generation",
        description: "Hosted open foundation models for conversational completions",
        models: [
          {
            id: "meta-llama/Llama-3.1-8B-Instruct",
            name: "Llama 3.1 8B Instruct",
            brain: "8B Open Weights Chat",
            role: "Fast lightweight general instruction model",
            rpm: "200 RPM",
            tpm: "—",
            rpd: "1k req / 5m",
            latency: "~240ms",
            pool: "Shared Hub Pool",
            highlight: true,
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
          {
            id: "meta-llama/Llama-3.2-3B-Instruct",
            name: "Llama 3.2 3B Instruct",
            brain: "3B Edge Conversational",
            role: "Ultra-fast low-memory conversational model",
            rpm: "200 RPM",
            tpm: "—",
            rpd: "1k req / 5m",
            latency: "~160ms",
            pool: "Shared Hub Pool",
            highlight: true,
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
          {
            id: "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B",
            name: "DeepSeek R1 Distill Qwen 32B",
            brain: "32B Deep Reasoning",
            role: "Chain-of-thought deep reasoning and math problem solving",
            rpm: "200 RPM",
            tpm: "—",
            rpd: "1k req / 5m",
            latency: "~480ms",
            pool: "Shared Hub Pool",
            ctx: "128k",
            maxOut: "4k",
            kind: "Reasoning CoT",
          },
          {
            id: "Qwen/Qwen2.5-72B-Instruct",
            name: "Qwen 2.5 72B Instruct",
            brain: "72B High Intelligence",
            role: "Flagship open weights reasoning, code and math",
            rpm: "200 RPM",
            tpm: "—",
            rpd: "1k req / 5m",
            latency: "~650ms",
            pool: "Shared Hub Pool",
            ctx: "128k",
            maxOut: "4k",
            kind: "High Intelligence",
          },
        ],
      },
      {
        name: "🔍 Vector Embeddings & Similarity",
        description: "Dense semantic text embeddings for knowledge bases and deduplication",
        models: [
          {
            id: "BAAI/bge-large-en-v1.5",
            name: "BGE Large EN v1.5",
            brain: "1024-dim Dense Vectors",
            role: "Primary high-accuracy English dense semantic retrieval (1024 dims)",
            rpm: "200 RPM",
            tpm: "—",
            rpd: "1k req / 5m",
            latency: "~463ms",
            pool: "Shared Hub Pool",
            highlight: true,
            ctx: "512",
            maxOut: "Embeddings",
            kind: "Vector Embedding",
          },
          {
            id: "BAAI/bge-small-en-v1.5",
            name: "BGE Small EN v1.5",
            brain: "384-dim Fast Vectors",
            role: "High-speed lightweight English vector retrieval",
            rpm: "200 RPM",
            tpm: "—",
            rpd: "1k req / 5m",
            latency: "~360ms",
            pool: "Shared Hub Pool",
            ctx: "512",
            maxOut: "Embeddings",
            kind: "Vector Embedding",
          },
          {
            id: "intfloat/multilingual-e5-large",
            name: "Multilingual E5 Large",
            brain: "1024-dim Multilingual",
            role: "Enterprise cross-lingual semantic search across 100+ languages",
            rpm: "200 RPM",
            tpm: "—",
            rpd: "1k req / 5m",
            latency: "~676ms",
            pool: "Shared Hub Pool",
            ctx: "512",
            maxOut: "Embeddings",
            kind: "Vector Embedding",
          },
          {
            id: "sentence-transformers/all-MiniLM-L6-v2",
            name: "All MiniLM L6 v2",
            brain: "384-dim Similarity",
            role: "Fast sentence similarity and text deduplication",
            rpm: "200 RPM",
            tpm: "—",
            rpd: "1k req / 5m",
            latency: "~310ms",
            pool: "Shared Hub Pool",
            ctx: "256",
            maxOut: "Embeddings",
            kind: "Vector Embedding",
          },
        ],
      },
      {
        name: "🏷️ Text Classification & Intent",
        description: "High-throughput sentiment analysis and intent detection routing",
        models: [
          {
            id: "distilbert/distilbert-base-uncased-finetuned-sst-2-english",
            name: "DistilBERT Sentiment SST-2",
            brain: "Sentiment & Intent Classifier",
            role: "High-speed sentiment analysis and intent detection",
            rpm: "200 RPM",
            tpm: "—",
            rpd: "1k req / 5m",
            latency: "~310ms",
            pool: "Shared Hub Pool",
            ctx: "512",
            maxOut: "Classifier",
            kind: "Classifier",
          },
        ],
      },
    ],
  },
  bazaarlink: {
    name: "BazaarLink",
    totalCapacity: "3,700 Points / day (20 RPM Global Limit)",
    poolType: "shared",
    poolBadge: "🟡 Shared 3,700 Points/Day Pool",
    poolSummary:
      "All BazaarLink free models share a single global account allowance of 3,700 points/day and 20 RPM limit. Supports built-in multi-model fallback arrays.",
    categories: [
      {
        name: "💬 Reasoning & Auto-Routing",
        description: "Large context reasoning and intelligent multi-cloud routing",
        models: [
          {
            id: "qwen/qwen3.7-flash:free",
            name: "Qwen 3.7 Flash Free",
            brain: "1M Context Alibaba Model",
            role: "Primary 1,000,000 context reasoning model",
            rpm: "20 RPM",
            tpm: "—",
            rpd: "3,700 pts/day",
            latency: "~4,748ms",
            pool: "Shared Account Pool",
            highlight: true,
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
          {
            id: "auto:free",
            name: "Auto-Router Free",
            brain: "Dynamic Free Router",
            role: "Dynamic auto-routing across healthiest high-speed endpoints",
            rpm: "20 RPM",
            tpm: "—",
            rpd: "3,700 pts/day",
            latency: "~1,347ms",
            pool: "Shared Account Pool",
            highlight: true,
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
        ],
      },
    ],
  },
  cerebras: {
    name: "Cerebras",
    totalCapacity: "Paid / BYOK (Requires Credit Card)",
    poolType: "isolated",
    poolBadge: "💳 Paid / BYOK Only (No Free Tier)",
    poolSummary:
      "Cerebras does not provide a permanent free tier. Requires adding a verified payment method in cloud.cerebras.ai (returns HTTP 402 otherwise).",
    categories: [
      {
        name: "⚡ Wafer-Scale Ultra-Fast Chat",
        description: "World-record speed inference at >1,800 tokens per second",
        models: [
          {
            id: "gpt-oss-120b",
            name: "GPT-OSS 120B Cerebras",
            brain: "120B Wafer-Scale Flagship",
            role: "120B flagship reasoning delivered at wafer-scale speed",
            rpm: "30 RPM",
            tpm: "60k TPM",
            rpd: "1,000 RPD",
            latency: "~180ms",
            pool: "CS-3 WSE Pool",
            highlight: true,
            ctx: "128k",
            maxOut: "4k",
            kind: "High Intelligence",
          },
          {
            id: "qwen-3.8-27b",
            name: "Qwen 3.8 27B Cerebras",
            brain: "27B Ultra-Fast Chat",
            role: "Instant sub-150ms response time for conversational agents",
            rpm: "30 RPM",
            tpm: "60k TPM",
            rpd: "1,000 RPD",
            latency: "~120ms",
            pool: "CS-3 WSE Pool",
            ctx: "128k",
            maxOut: "4k",
            kind: "Chat",
          },
        ],
      },
    ],
  },
};
